### ISSUE TITLE
Question re. the naming of intermediate (unobserved) noisy relations

### ISSUE THREAD

**Issue by emilyfertig** [probcomp/hierarchical-irm#189]
If I have

```
class A
  name ~ string

class B
  a ~ A
  
class C
  a ~ A
  b ~ B

class D
  c ~ C

class Record
  d ~ D

observe
  d.c.a.name as name1
  d.c.b.a.name as name2
```

Then the resulting relations for Model 6/7 are

```
R1: A -> str
NR1: A, C | R1 -> str
NR2: A, B | R1 -> str
NR3: A, C, D | NR1 -> str
NR4: A, B, C | NR2 -> str
NR5: A, B, C, D | NR4 -> str
name1: A, C, D, R | NR3 -> str
name2: A, B, C, D, R | NR5 -> str
``` 
(Is that right?) Given the current naming scheme for noisy relations, are NR3 and NR5 both named `D:c::A:name`? (If so, this is a bug and they should have distinct names.)

**Comment by ThomasColthurst** [comment]
Those relations are correct for Model 6 given the current spec (but also see https://github.com/probcomp/hierarchical-irm/issues/188 about whether we want to keep the current non-spec behavior as an option).  

With the current implementation, both NR3 and NR5 would be conditioned on exactly A, C, D and would have the name D:c::A:name.  And you are correct that that would also be non-spec, because the spec says there should be a noisy relation for every combination of (class, path, attribute).

The only additional thing I might say is that when we can merge two noisy relations into one (for example, when they are conditioned on the same domains and share the same base relation), we probably should for reasons of parameter sharing.  But as this example shows, that will be less possible if/when we reduce the number of domains the noisy relations are conditioned on.
