### ISSUE TITLE
irm.logp(x) != irm.logp_score() after irm.incorporate(x)

### ISSUE THREAD

**Issue by ThomasColthurst** [probcomp/hierarchical-irm#66]
Line 36 of irm_test.cc tests this.  Is this a bug in the IRM code, or am I misunderstanding something?

**Comment by srvasude** [comment]
FWIW from our discussion on Wednesday / Emily's comments and some unit testing, this shouldn't be an issue. I have added a test in a PR I'll send out that computes relations on a single data point, that irm.logp(x) = irm.logp_score(). It should be true in this case since there is only a single element cluster, so there's nothing to marginalize over (vs. when we have 2 elements they can be in the same or different clusters, and incorporating forces a choice).
